"""empty message

Revision ID: 4ddb93a7ba3b
Revises: 
Create Date: 2025-10-26 10:07:30.696129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import shared # type: ignore

# revision identifiers, used by Alembic.
revision: str = '4ddb93a7ba3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('active', 'temporary_ban', 'permanent_ban', 'self_removal', 'forced_removal', name='accessstatus'), nullable=False),
    sa.Column('status_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status_description', sa.String(length=128), nullable=True),
    sa.Column('create', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='skymp-masterapi'
    )
    op.create_table('server',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'temporary_ban', 'permanent_ban', 'self_removal', 'forced_removal', name='accessstatus'), nullable=False),
    sa.Column('status_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status_description', sa.String(length=128), nullable=True),
    sa.Column('create', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['skymp-masterapi.user.user_id'], ),
    sa.PrimaryKeyConstraint('uuid'),
    schema='skymp-masterapi'
    )
    op.create_table('user_account',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('email', 'discord', name='userprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=320), nullable=False),
    sa.Column('password_hash', shared.models.custom_type.SecretByteType(length=128), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('reg_ip', postgresql.INET(), nullable=False),
    sa.Column('last_ip', postgresql.INET(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(provider = 'email' AND password_hash IS NOT NULL) OR (provider != 'email')", name='chk_email_requires_password'),
    sa.ForeignKeyConstraint(['user_id'], ['skymp-masterapi.user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('provider_id'),
    schema='skymp-masterapi'
    )
    op.create_table('user_public_info',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['skymp-masterapi.user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    schema='skymp-masterapi'
    )
    op.create_table('favorite_server',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['server_uuid'], ['skymp-masterapi.server.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['skymp-masterapi.user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'server_uuid'),
    schema='skymp-masterapi'
    )
    op.create_table('game_session',
    sa.Column('session_id', shared.models.custom_type.ULIDType(length=26), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_uuid', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=1024), nullable=False),
    sa.Column('reg_ip', postgresql.INET(), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('create', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_uuid'], ['skymp-masterapi.server.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['skymp-masterapi.user.user_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    schema='skymp-masterapi'
    )
    op.create_table('refresh_token',
    sa.Column('account_user_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=32), nullable=False),
    sa.Column('jti', sa.String(length=26), nullable=False),
    sa.Column('token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_user_id'], ['skymp-masterapi.user_account.user_id'], ),
    sa.PrimaryKeyConstraint('account_user_id', 'device'),
    sa.UniqueConstraint('jti'),
    schema='skymp-masterapi'
    )
    op.create_table('report_server',
    sa.Column('id', shared.models.custom_type.ULIDType(length=26), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('server_uuid', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('create', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['skymp-masterapi.user.user_id'], ),
    sa.ForeignKeyConstraint(['server_uuid'], ['skymp-masterapi.server.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='skymp-masterapi'
    )
    op.create_table('server_credential',
    sa.Column('server_uuid', sa.UUID(), nullable=False),
    sa.Column('secret_hash', shared.models.custom_type.SecretByteType(length=128), nullable=False),
    sa.Column('allowed_ips', postgresql.INET(), nullable=True),
    sa.Column('last_ip', postgresql.INET(), nullable=True),
    sa.Column('last_used', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('create', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_uuid'], ['skymp-masterapi.server.uuid'], ),
    sa.PrimaryKeyConstraint('server_uuid'),
    schema='skymp-masterapi'
    )
    op.create_table('server_public_info',
    sa.Column('server_uuid', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('host', postgresql.INET(), nullable=False),
    sa.Column('main_port', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=True),
    sa.Column('gamemode_type', sa.Enum('none', 'sandbox', 'roleplay', 'adventure', 'minigames', 'pvp', 'pve', 'mmo', name='servergamemode'), nullable=False),
    sa.Column('game_version', sa.String(length=32), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_uuid'], ['skymp-masterapi.server.uuid'], ),
    sa.PrimaryKeyConstraint('server_uuid'),
    sa.UniqueConstraint('host', 'main_port', name='uc_host_port'),
    schema='skymp-masterapi'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_public_info', schema='skymp-masterapi')
    op.drop_table('server_credential', schema='skymp-masterapi')
    op.drop_table('report_server', schema='skymp-masterapi')
    op.drop_table('refresh_token', schema='skymp-masterapi')
    op.drop_table('game_session', schema='skymp-masterapi')
    op.drop_table('favorite_server', schema='skymp-masterapi')
    op.drop_table('user_public_info', schema='skymp-masterapi')
    op.drop_table('user_account', schema='skymp-masterapi')
    op.drop_table('server', schema='skymp-masterapi')
    op.drop_table('user', schema='skymp-masterapi')
    # ### end Alembic commands ###
